
services:
  go-app:
    container_name: go-app
    image: go-api-image
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: go_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "0220"
      DB_NAME: postgres
    depends_on:
      go_db:
        condition: service_healthy
  go_db:
    container_name: go_db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "0220"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}